name: Sync

on:
  push:
    branches: "**"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Sync with remote repository
        run: |
          rm -rf .git
          git init
          git remote add origin https://hydralauncher:${{ secrets.HYDRA_GITHUB_SECRET }}@github.com/hydralauncher/hydra
          git config --global init.defaultBranch main
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          git checkout -b main
          git add .
          git commit -a -m "$GITHUB_SHA"
          git push origin main --force
